ALTER TABLE clips_v2 ADD COLUMN IF NOT EXISTS template_id VARCHAR(255);
ALTER TABLE clips_v2 ADD COLUMN IF NOT EXISTS background JSONB;
ALTER TABLE clips_v2 ADD COLUMN IF NOT EXISTS subtitle JSONB;
ALTER TABLE IF EXISTS youtube_uploads ALTER COLUMN privacy_status SET DEFAULT 'public';
